[package]
name = "picker"
version = "0.1.0"
authors = ["Aram Drevekenin <aram@poor.dev>"]
edition = "2018"

[dependencies]
zellij-tile = { version = "0.43.0", path = "/home/aram/code/zellij/zellij-tile" }
fuzzy-matcher = "0.3.7"
