name: Release Build

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Build release binary
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasip1

      - name: Build release binary
        run: cargo build --release --target wasm32-wasip1

      - name: Upload binary to release
        uses: softprops/action-gh-release@v1
        with:
          files: ./target/wasm32-wasip1/release/grab.wasm
