name: Release Build

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag to upload to (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  build:
    name: Build release binary
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasip1

      - name: Build release binary
        run: cargo build --release --target wasm32-wasip1

      - name: Upload binary to release
        uses: softprops/action-gh-release@v1
        with:
          files: ./target/wasm32-wasip1/release/grab.wasm
          tag_name: ${{ github.event.inputs.tag || github.event.release.tag_name }}
