name: Release Build

on:
  release:
    types: [published]

jobs:
  build:
    name: Build release binary
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasip1

      - name: Build release binary
        run: cargo build --release

      - name: Upload binary to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/wasm32-wasip1/release/grab.wasm
          asset_name: grab.wasm
          asset_content_type: application/wasm
